## 熟悉矩阵操作
矩阵的意义非常重要，它可以作用在一个具体的向量上，使其空间位置发生变换  
它可以看作是n个m维列向量从左到右并排摆放，也可以看作是m个n维行向量从上到下进行叠放

In [1]:
import numpy as np
A = np.array([[1, 2],
              [3, 4],
              [5, 6],
              [7, 8]])
print(A)
print(A.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


转置， 零矩阵， 对角矩阵， 单位矩阵

In [5]:
print(A.T)
print(np.zeros([4, 1]))
print(np.diag([1, 2, 3, 4, 5]))
print(np.eye(3))

[[1 3 5 7]
 [2 4 6 8]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


矩阵乘法

In [11]:
B = A.T
print(A)
print(B)
print(np.dot(A, B))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 3 5 7]
 [2 4 6 8]]
[[  5  11  17  23]
 [ 11  25  39  53]
 [ 17  39  61  83]
 [ 23  53  83 113]]


## 矩阵乘以向量： 改变向量的空间位置
矩阵与向量的乘法一般写成 Ax 形式  
这种写法便于描述向量x的空间位置在矩阵A的作用下进行变换的过程

In [12]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])
x = np.array([[4, 5]]).T
print(np.dot(A, x))

[[14]
 [32]
 [50]]


在指定矩阵的乘法作用下，原始空间中的向量被映射转换到了目标空间的新坐标  
向量的空间位置由此发生了变化
甚至在映射之后，目标空间的维数相较于原始空间都有可能发生改变