## 对称矩阵的性质总结  
对于任意一个$m*n$形状的矩阵$A$,有如下性质
1. 矩阵$A$和转置矩阵$A^T$相乘的结果$A^TA$和$AA^T$都是对称矩阵
2. 矩阵$A^TA$和矩阵$AA^T$都能够被对角化，且都可以通过矩阵分解，获得一组标准正交的特征向量$S=Q\Lambda Q^{-1}=Q\Lambda Q^T$
3. 矩阵$A^TA$和矩阵$AA^T$分别是n阶和m阶的方阵，它们的秩相等
4. 对于矩阵$A^TA$而言，它的特征值一定都是非负的，特别地，如果矩阵$A$的列向量满足线性无关，那么它的特征值全部为正，即为正定矩阵
5. 矩阵$A^TA$和矩阵$AA^T$拥有完全相同的非零特征值，非零特征值的个数与矩阵$A$的秩相等

## 矩阵分布的度量  
方差度量了变量自身的离散程度，而协方差则表征了两组随机变量之间的相关程度
#### 1. 期望与方差

In [7]:
import numpy as np

a = np.random.randint(0, 10, (2, 3))
print(a)
print(a.mean())
print(np.var(a))

[[8 9 9]
 [2 5 2]]
5.833333333333333
9.13888888888889


#### 2.协方差

In [5]:
import numpy as np
a, b = np.random.rand(2, 4)
print(a)
print(b)
print(np.cov(a, b))
print(len(a) - 1)
print(np.dot(a - np.mean(a), b - np.mean(b)) / (len(a) - 1))

[0.96810646 0.92428043 0.88022276 0.9655652 ]
[0.87494375 0.74739207 0.62016251 0.64764208]
[[0.00171496 0.00269927]
 [0.00269927 0.01331179]]
3
0.002699273978469004
